package domain.gameLogic;

public enum GameEventType {
	RANDOMISE_LEVELS,
	SAVE_LEVEL,
	PAUSE_GAME,
	RESUME_GAME,
	CLOSE_GAME,
	OPEN_SAVE_GAME_MENU,
	OPEN_LOAD_GAME_MENU,
	OPEN_HELP_GAME_MENU, 
	CLOSE_LOAD_MENU, LOGGED_IN, PLAY_GAME, CLOSE_DIALOG_WINDOW, OPEN_MAIN_MENU, LOST_GAME, WON_GAME,
}
